### ISSUE TITLE
Nuova versione verificac19-sdk con supporto CRL

### ISSUE THREAD

**Issue by astagi** [DCC-API/dcc-node-api#2]
Ciao @alessiosantocs! ho rilasciato la nuova versione, ci sono alcune breaking change oltre che il supporto a MongoDB.

Note di rilascio: https://github.com/italia/verificac19-sdk/releases

Per qualsiasi supporto / richiesta di chiarimento fammi sapere!

**Comment by alessiosantocs** [comment]
Grazie mille. Aggiorniamo nei prossimi giorni.
Grazie del tuo lavoro!

**Comment by astagi** [comment]
Figurati @alessiosantocs a presto!

**Comment by alessiosantocs** [comment]
Ho aggiornato la versione della libreria e rilasciato una nuova versione dell'applicazione.
